FROM python:3.4-alpine

RUN mkdir -p /code
WORKDIR /code/dockering

COPY dockering/requirements.txt dockering/requirements_test.txt /code/dockering/

RUN pip3 install --upgrade pip && pip3 install -r requirements_test.txt

COPY . /code/
