version: "2.3"
services:
  # when used as an "override" compose file, will merge with docker-compose.yml
  web:
    stdin_open: true
    tty: true
    # TODO: entrypont runserver so breakpoints can be used (seg fault)
    #entrypoint: "python3 manage.py load_es_data"
