version: "2.3"
services:
  # TODO: Kibana
  # TODO: Web app
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      - discovery.type=single-node
    networks:
      - country_search
networks:
  country_search:
